---

services:
  hima-website:
    ports:
      - '3000:3000'
    platform: linux/x86_64
    image: ghcr.io/vichannnnn/hima-website/hima-website:latest
    container_name: hima-website
    networks:
      - hima-website-network
    command: pnpm run start
    restart:
      always

networks:
  hima-website-network:
    name: hima-website-network
    driver: bridge