---
version: '3.8'

services:
  hima-website:
    ports:
      - '3000:3000'
    image: hima-website-v2
    container_name: hima-website
    networks:
      - hima-website-network
    command: bun run start
    restart:
      always

networks:
  hima-website-network:
    name: hima-website-network
    driver: bridge